theme: minima

title: VisionAI.ID
description: Indonesia Vision AI Landing Page
author: "Indonesia Vision AI Team"

base_url: /indonesia-vision-ai.github.io
repository: indonesia-vision-ai/indonesia-vision-ai.github.io

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/frontpage.md
  
include:
    - _pages

exclude:
    - README.md
