theme: jekyll-theme-minimal

title: VisionAI.ID
description: Indonesia Vision AI Landing Page
author: "Indonesia Vision AI Team"


minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/frontpage.md
  
include:
    - _pages

exclude:
    - README.md
